# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02MPC04DPEntitySelectionleftslider():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02MPC04DPEntitySelectionleftslider(self):
    # Test name: TC02_M_PC04_DP_Entity Selection left slider
    # 1 abrir pagina en la que se va a testear
    self.driver.get('http://09384038:ARbg95917284.@pepwds34276.cww.pep.pvt/ReportServer_SQLLTMMES8005P/Pages/ReportViewer.aspx?%2fMES+Reports%2fSub%20Report%20Menu&UseGlobalDescriptions=True&ReportName=Packaging%20Summary&Category=1&RDLName=Summary%20Report&rs:Command=Render')

    
    # espero a que cargue
    time.sleep(8)
    
    # # click en By date
    self.driver.find_element(By.XPATH, '//body[1]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[3]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/a[1]/div[1]').click()
    time.sleep(2)

