# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC04M01DPDowntimetimes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC04M01DPDowntimetimes(self):
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    downTimeBt = 'document.querySelector("#root_pagemashupcontainer-6_ContainedMashup-13_ptcstabset-237").shadowRoot.querySelector("ptcs-tabs > ptcs-tab:nth-child(5) > ptcs-label").shadowRoot.querySelector("#label")'
    #variable para show all data
    showAlldata='document.querySelector("#root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85-external-wc").shadowRoot.querySelector("#chunker > div > div > ptcs-list-item:nth-child(1)")'
    #variable de las filas
    # 3 | waitForElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_mashupcontainer-5_gridadvanced-109 | 50000
    WebDriverWait(self.driver, 50).until(expected_conditions.presence_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_mashupcontainer-5_gridadvanced-109")))
    # 4 | click | id=root_pagemashupcontainer-6_ContainedMashup-13_ptcstabset-237 | 
    self.driver.execute_script(f'return {downTimeBt}').click()
    # 5 | waitForElementPresent | xpath=//div[@id='root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_radiobuttonlist-99']/table/tbody/tr/td[3]/span | 50000
    WebDriverWait(self.driver, 50).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_radiobuttonlist-99\']/table/tbody/tr/td[3]/span")))
    # 6 | click | css=#root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_radiobuttonlist-99 .widget-radio-button-item:nth-child(3) > .radio-button-state-name | 
    self.driver.find_element(By.CSS_SELECTOR, "#root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_radiobuttonlist-99 .widget-radio-button-item:nth-child(3) > .radio-button-state-name").click()
    # 7 | waitForElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85 | 50000
    WebDriverWait(self.driver, 50).until(expected_conditions.presence_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85")))
    # 8 | click | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85 | 
    time.sleep(4)
    self.driver.find_element(By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85").click()
    # 9 | waitForElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85-external-wc | 30000
    WebDriverWait(self.driver, 60).until(expected_conditions.presence_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsdropdown-85-external-wc")))
    # 10 | click | xpath=//*[@id="chunker"]/div/div/ptcs-list-item[1]/ptcs-div | 
    time.sleep(5)
    self.driver.execute_script(f'return {showAlldata}').click()
    time.sleep(4)
    # 11 | click | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsbutton-14 | 
    self.driver.find_element(By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-91_mashupcontainer-94_ptcsbutton-14").click()
   

if __name__== '__main__':
  pytest.main()