# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02MPC04DPEntitySelectionleftslider():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02MPC04DPEntitySelectionleftslider(self):
    # Test name: TC02_M_PC04_DP_Entity Selection left slider
    # Step # | name | target | value
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    # 2 | waitForElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-12_ContainedMashup-141_flexcontainer-79 | 30
    WebDriverWait(self.driver, 0.03).until(expected_conditions.presence_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-12_ContainedMashup-141_flexcontainer-79")))
    # 3 | click | xpath=//div[@id='flexcontainer-103-expand-btn']/i | 
    self.driver.find_element(By.XPATH, "//div[@id=\'flexcontainer-103-expand-btn\']/i").click()
    # 4 | click | xpath=//ptcs-dropdown[@id='root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100'] | 
    self.driver.find_element(By.XPATH, "//ptcs-dropdown[@id=\'root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100\']").click()
    # 5 | click | xpath=//ptcs-list[@id='root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100-external-wc'] | 
    self.driver.find_element(By.XPATH, "//ptcs-list[@id=\'root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100-external-wc\']").click()
    # 6 | click | xpath=//ptcs-button[@id='cell_PlantModelSelectionForNavigation_RepeaterButton-9_ptcsbutton-43'] | 
    self.driver.find_element(By.XPATH, "//ptcs-button[@id=\'cell_PlantModelSelectionForNavigation_RepeaterButton-9_ptcsbutton-43\']").click()
    # 7 | click | xpath=//ptcs-button[@id='cell_PlantModelSelectionForNavigation_RepeaterButton-9_ptcsbutton-43'] | 
    self.driver.find_element(By.XPATH, "//ptcs-button[@id=\'cell_PlantModelSelectionForNavigation_RepeaterButton-9_ptcsbutton-43\']").click()
    # 8 | echo | Se ha seleccionado la linea | 
    print("Se ha seleccionado la linea")
  
