# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC03MPC01DPEfficiencyCapacityWasteandDowntimevalues():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC03MPC01DPEfficiencyCapacityWasteandDowntimevalues(self):
    # Test name: TC03_M_PC01_DP_Efficiency, Capacity, Waste and Downtime values
    # Step # | name | target | value
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    # 2 | waitForElementPresent | css=#root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced > .objbox | 30000
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced > .objbox")))
    # 3 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[2] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]")
    assert len(elements) > 0
    # 4 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[3] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[3]")
    assert len(elements) > 0
    # 5 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[4] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[4]")
    assert len(elements) > 0
    # 6 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[5] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[5]")
    assert len(elements) > 0
    # 7 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[6] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[6]")
    assert len(elements) > 0
    # 8 | assertElementPresent | xpath=//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[7] | 
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[7]")
    assert len(elements) > 0
    # 9 | echo | ¡¡¡¡Todas las lineas se visualizan en pantalla!!!! | 
    print("¡¡¡¡Todas las lineas se visualizan en pantalla!!!!")
  
