# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02MPC01DPEntitySelectionleftslider():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02MPC01DPEntitySelectionleftslider(self):
    # Test name: TC02_M_PC01_DP_Entity Selection left slider
    # Step # | name | target | value
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    # 2 | waitForElementVisible | id=root_pagemashupcontainer-6_ContainedMashup-13_ptcstabset-237 | 5000
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ptcstabset-237")))
    # 3 | click | css=#flexcontainer-103-expand-btn > .tw-icon | 
    self.driver.find_element(By.CSS_SELECTOR, "#flexcontainer-103-expand-btn > .tw-icon").click()
    # 4 | assertElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-105_mashup-root | 
    # se muestra el menu de areas y lineas de produccion
    elements = self.driver.find_elements(By.ID, "root_pagemashupcontainer-6_ContainedMashup-105_mashup-root")
    assert len(elements) > 0
  
