# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
import time
driver = webdriver.Chrome()
vars = {}



# Test name: TC03_M_PC02_DP_Efficiency, Capacity, Waste and Downtime values
# Step # | name | target | value
# 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
# 2 | waitForElementPresent | id=root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75 | 30000
WebDriverWait(driver, 60).until(expected_conditions.presence_of_element_located((By.XPATH, '//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table')))
time.sleep(7)
filas=len(driver.find_elements(By.XPATH,'//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr'))
columnas=len(driver.find_elements(By.XPATH,'//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[1]/th'))

example= driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr[2]/td[1]')

print(example)

print(filas)
print(columnas)

for f in range(2,filas+1) :
  for c in range(3,columnas+1):
    dato=driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td['+str(c)+']').text
    if c == 3 and int(dato) <= 100:
      assert "error" ==f'El Set Point esta de la linea {(f)-1} esta en 100 o más'
    elif c==4 and int(dato) >=100:
      assert "error" ==f'El Name Plate esta de la linea {(f)-1} esta en 100 o más'
    elif c==5 and int(dato) >=100:
      assert "error" ==f'El NE esta de la linea {(f)-1} esta en 100 o más'
    elif c==6 and int(dato) <=0:
      assert "error" ==f'El D esta de la linea {(f)-1} esta en 100 o más'
    elif c==7 and int(dato) >=100:
      assert "error" ==f'El T esta de la linea {(f)-1} esta en 100 o más'
    elif c==8 and int(dato) >=100:
      assert "error" ==f'El W esta de la linea {(f)-1} esta en 100 o más'
    print(dato,end="   ")
  print("\n")


