# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC02MPC03DPEntitySelectionleftslider():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC02MPC03DPEntitySelectionleftslider(self):
    # Test name: TC02_M_PC03_DP_Entity Selection left slider
    # Step # | name | target | value
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    # 2 | waitForElementPresent | xpath=//ptcs-label[@id='root_pagemashupcontainer-6_ContainedMashup-12_ContainedMashup-134_ptcslabel-21'] | 30
    WebDriverWait(self.driver, 0.03).until(expected_conditions.presence_of_element_located((By.XPATH, "//ptcs-label[@id=\'root_pagemashupcontainer-6_ContainedMashup-12_ContainedMashup-134_ptcslabel-21\']")))
    # 3 | click | id=flexcontainer-103-expand-btn | 
    self.driver.find_element(By.ID, "flexcontainer-103-expand-btn").click()
    # 4 | click | id=root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100 | 
    self.driver.find_element(By.ID, "root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100").click()
    # 5 | click | id=root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100-external-wc | 
    self.driver.find_element(By.ID, "root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100-external-wc").click()
    # 6 | assertText | id=root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100 | Potato Chips
    assert self.driver.find_element(By.ID, "root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100").text == "Potato Chips"
    # 7 | echo | Se ha seleccionado el area de potatos | 
    print("Se ha seleccionado el area de potatos")
  
