# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC03MPC02DPEfficiencyCapacityWasteandDowntimevalues():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC03MPC02DPEfficiencyCapacityWasteandDowntimevalues(self):
    self.driver.get("https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75")))
    self.vars["setPoint"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]").text
    self.vars["namePlate"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[4]").text
    self.vars["NE"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[5]").text
    self.vars["D"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[6]").text
    self.vars["T"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[7]").text
    self.vars["W"] = self.driver.find_element(By.XPATH, "//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[8]").text
    if self.driver.execute_script("return (arguments[0]>=100)", self.vars["setPoint"]):
      print("SetPoint de la linea 1 esta a mas o igual a 100")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "SETPOINT IGUAL o MAYOR A 100")
    elif self.driver.execute_script("return (arguments[0]>=100)", self.vars["namePlate"]):
      print("Name Plate de la linea 1 esta a mas o igual a 100")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "NAMEPLATE IGUAL o MAYOR A 100")
    elif self.driver.execute_script("return (arguments[0]>=100)", self.vars["NE"]):
      print("NE de la linea 1 esta a mas o igual a 100")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "NE IGUAL o MAYOR A 100")
    elif self.driver.execute_script("return (arguments[0]<=0)", self.vars["D"]):
      print("D de la linea 1 esta a menos o igual a 0")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "D IGUAL o MENOR A 100")
    elif self.driver.execute_script("return (arguments[0]>=100)", self.vars["T"]):
      print("T de la linea 1 esta a mas o igual a 100")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "D IGUAL o MAYOR A 100")
    elif self.driver.execute_script("return (arguments[0]>=100)", self.vars["W"]):
      print("W de la linea 1 esta a mas o igual a 100")
      assert(self.vars["xpath=//*[@id=\"root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_gridadvanced-109-grid-advanced\"]/div[2]/table/tbody/tr[2]/td[3]"] == "W IGUAL o MAYOR A 100")
    elif self.driver.execute_script("return (true)"):
      print("¡¡¡¡¡¡¡¡¡¡¡La linea esta fucnionando conrectamente!!!!!!!!!!!!!")
  
