# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import sys,os
p = os.path.abspath('..')
sys.path.insert(1, p)
from utilities.ligasPlanta import LIGAPRINCIPAL

class TestTUC04_M_TC05_PC1_DP_Wastetab():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('../../externalLibraries/chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tUC04_M_TC05_PC1_DP_Wastetab(self):
    # Test name: test_tUC04_M_TC05_PC1_DP_Wastetab
    # 1 | open | https://09384038:ARbg95917284.@meswebgsftmexicali.azure.intra.pepsico.com/Thingworx/Runtime/index.html#master=PepsiCo_Master&mashup=MES_Dashboard&__applyThemeName=PepsiCo%20Default%20Theme&_refreshTS=1670527225809 | 
    self.driver.get(LIGAPRINCIPAL)
    # WebDriverWait(self.driver, 100).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'root_pagemashupcontainer-6_ContainedMashup-13_ContainedMashup-75_mashupcontainer-5_gridadvanced-109-bounding-box\']/div[3]")))
    time.sleep(15)
    # 2 click burger menu | click | id=burgerButton | 
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[2]/div[2]").click()
    time.sleep(4)
    # 3 click en dropdown 
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[1]/div[1]/div/div[3]/div/div[2]/div/div/div[2]/div/div[1]/div/div[4]/ptcs-dropdown//ptcs-hbar/ptcs-list-item").click()
    time.sleep(4)
    # 4 | click | papa departamento | 
    self.driver.execute_script('return document.querySelector("#root_pagemashupcontainer-6_ContainedMashup-105_ptcsdropdown-100-external-wc").shadowRoot.querySelector("#chunker > div > div > ptcs-list-item:nth-child(1) > ptcs-div")').click()
    time.sleep(5)
    # 5 | click | click en boton de packaging |
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[1]/div[1]/div/div[3]/div/div[2]/div/div/div[2]/div/div[3]/div/div[2]/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[2]/div/div[3]/div/div/ptcs-button").click()
    time.sleep(20)
    # 6 | click | click en pestaña de downtime
    self.driver.execute_script('return document.querySelector("#root_pagemashupcontainer-6_ContainedMashup-13_ptcstabset-237").shadowRoot.querySelector("ptcs-tabs > ptcs-tab:nth-child(9) > ptcs-label").shadowRoot.querySelector("#label")').click()
    time.sleep(4)
    # ----------------------
    # 7 | click | en boton de area chronological Events
    self.driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div/ptcs-tab-set/ptcs-mb-container[5]/div/div/div/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div[3]/table/tbody/tr/td[3]/span').click()
    time.sleep(9)
    # 8 | click | en un evento de los que hayan durado menos tiempo
    self.driver.find_elements

    # 12 defino una variable que contiene los mensajes de error
    errores="\n  "

    # 13 recorro la tabla en busca del equipo que no esta en funcionamiento (ROJO)
    tablePath='//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody'
    filas=self.driver.find_elements(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr')
    columnas=self.driver.find_elements(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr[2]/td')
    filas=len(filas)
    columnas=len(columnas)
    for f in range(2,filas+1):
      departamento=self.driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td[1]').text
      linea=self.driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td[2]').text
      tubo=self.driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td[3]').text
      
      for c in range(1, columnas+1):
        equipo=self.driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td['+str(c)+']')
        nombreEquipo=self.driver.find_element(By.XPATH,'//*[@id="root_pagemashupcontainer-6_mashupcontainer-142_gridadvanced-4-grid-advanced"]/div[2]/table/tbody/tr['+str(f)+']/td['+str(c)+']').text
        equipoClase=equipo.get_attribute("class")
        if equipoClase=="twdhtmlxcell cell_style2" and len(nombreEquipo)>3:
            errores+=f'El equipo {nombreEquipo} del departamento {departamento} linea: {linea} tubo: {tubo} esta fallando \n'

    assert len(errores)<5,  errores
    

if __name__=='__main__':
  pytest.main()